spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    root: WARN
    com.maansarovar.restaurant: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
